spring.application.name=inmueble-api
server.port=8081
# esta configuracion utiliza la base de datos en memoria.
spring.datasource.url=jdbc:h2:file:./data/inmuebledb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# muestra los querys por consola.
spring.jpa.show-sql=true

############################################
# Configuración de Hibernate (JPA)
############################################

# Estrategia de modificación de la base de datos:
#
# ddl-auto=create       ? Crea toda la estructura desde cero (borra lo anterior).
# ddl-auto=create-drop  ? Crea la base y la elimina al cerrar la aplicación.
#ddl-auto=update
# ddl-auto=none         ? No modifica nada. Se usa cuando ya existe la base.

spring.jpa.hibernate.ddl-auto=update
